settings:
  server_url: http://0.0.0.0:9393
sizes:
  -
    width: 300
    height: 250
  -
    width: 600
    height: 400
templates:
  -
    name: home
    url: /
    ttl: 30
  -
    name: tube
    url: /tube
    ttl: 60