settings:
  server_url: http://0.0.0.0:9292
sizes:
  -
    width: 300
    height: 250
  -
    width: 600
    height: 400
templates:
  -
    name: home
    url: /
    ttl: 30
  -
    name: test
    url: /test
    ttl: 60